export const ACTION_TYPES = Object.freeze({
  SET_INITIAL_MESSAGES: 'SET_INITIAL_MESSAGES',
  POST_MESSAGE: 'POST_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  DELETE_ALL_MESSAGES: 'DELETE_ALL_MESSAGES',
  TOGGLE_SORT: 'TOGGLE_SORT',
});
